version: '3.8'
services:
  server:
    build: ./server-python
    ports:
      - "5000:5000"
    networks:
      - monitor-network

  agent:
    build: ./agent-go
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:5000/report
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge
